name: Deploy to Github Pages
on:
  push:
    branches: [master]
env:
  GIT_USER: techstay
  GIT_EMAIL: lovery521@gmail.com
  DEPLOY_REPO: techstay/techstay.github.io
  DEPLOY_BRANCH: gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install Npm Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Configuration Environment
        env:
          HEXO_DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
      - name: Deploy Hexo
        run: |
          npm run deploy
